### ISSUE TITLE
dependency errors "Uncaught ReferenceError: $ is not defined"

### ISSUE THREAD

**Issue by fluxsaas** [gosquared/gosquared-rails#1]
Hey,

i have a dependency error when loading the javascript via the gem. if anyone else runs in a problem like that, here is a solution:

layout/application.html.erb:

```
    <script>
      !function(g,s,q,r,d){r=g[r]=g[r]||function(){(r.q=r.q||[]).push(
      arguments)};d=s.createElement(q);q=s.getElementsByTagName(q)[0];
      d.src='//d1l6p2sc9645hc.cloudfront.net/tracker.js';q.parentNode.
      insertBefore(d,q)}(window,document,'script','_gs');
      _gs('TOKEN', false);
    </script>
```

track.js

```
function track() {
    _gs('track');
}

$(document).on('turbolinks:before-render', function(event) {

  var chat = $('[id^="gs_"]');
  if (chat.length) {
    chat
      .detach()
      .appendTo(event.originalEvent.data.newBody);
  }
})

$(document).on('turbolinks:render', function() {
  try {
    window.dispatchEvent(new Event('resize'));
  } catch (e) {}
})

$(document).on('turbolinks:load', track)
```
do not forget to add: `skip_after_action :add_gosquared_script` to the application_controller.rb

**Comment by russellvaughan** [comment]
Thanks very much for raising this. As far as solution, adding ```skip_after_action :add_gosquared_script``` to the application_controller.rb, this will stop the tracking code injecting across all views - so may not be ideal as its one of the core features of the gem. 

I will have to look into this as it appears that this javascript is being called before your jQuery is being loaded, which shouldn't be the case as the GoSquared script should be the last script loaded before your closing <head> tag.

**Comment by russellvaughan** [comment]
updated Readme now to reflect JQuery dependency
