### ISSUE TITLE
Problems with Injector, gem not working with latest Rails

### ISSUE THREAD

**Issue by pdrlps** [gosquared/gosquared-rails#3]
I was setting up the gem with the latest Rails and I found a critical issue: the gem causes Rails to crash (the engine won't even start and the generator will not work).

This happens because the "append_after_filter" on Injector::Filter is not working. I changed the raw gem code to "append_after_action" and it is working now.

**Comment by russellvaughan** [comment]
Pedro. Thank you very much for notifying me. I will look at this ASAP and get it rectified.

**Comment by russellvaughan** [comment]
updated and fixed in https://github.com/gosquared/gosquared-rails/commit/22e70e65dfbc891ebec75571d0663743aa4657b4
